// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJMNFgoNTv9vLNquq2XP_0NBvEv3RLggs',
    appId: '1:65152885570:web:a2ebffe90bc82db88d1edb',
    messagingSenderId: '65152885570',
    projectId: 'ecommerce-01-307ed',
    authDomain: 'ecommerce-01-307ed.firebaseapp.com',
    storageBucket: 'ecommerce-01-307ed.firebasestorage.app',
    measurementId: 'G-EZXC0ZGPE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXalr5DCSCkbFejiphXIZtc1Le61hE8Mk',
    appId: '1:65152885570:android:1553af5068ca532f8d1edb',
    messagingSenderId: '65152885570',
    projectId: 'ecommerce-01-307ed',
    storageBucket: 'ecommerce-01-307ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1o34DVa0EV12qERPkokskHTAKqbO_5hQ',
    appId: '1:65152885570:ios:9bb92f8bdeb9fb408d1edb',
    messagingSenderId: '65152885570',
    projectId: 'ecommerce-01-307ed',
    storageBucket: 'ecommerce-01-307ed.firebasestorage.app',
    iosBundleId: 'com.example.clotEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1o34DVa0EV12qERPkokskHTAKqbO_5hQ',
    appId: '1:65152885570:ios:9bb92f8bdeb9fb408d1edb',
    messagingSenderId: '65152885570',
    projectId: 'ecommerce-01-307ed',
    storageBucket: 'ecommerce-01-307ed.firebasestorage.app',
    iosBundleId: 'com.example.clotEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJMNFgoNTv9vLNquq2XP_0NBvEv3RLggs',
    appId: '1:65152885570:web:cbce20de955d55718d1edb',
    messagingSenderId: '65152885570',
    projectId: 'ecommerce-01-307ed',
    authDomain: 'ecommerce-01-307ed.firebaseapp.com',
    storageBucket: 'ecommerce-01-307ed.firebasestorage.app',
    measurementId: 'G-81CX3H56FQ',
  );
}
